//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotEduWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Eleves
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eleves()
        {
            this.Notes = new HashSet<Notes>();
        }
    
        public int ID_eleve { get; set; }
        [DisplayName("Nom élève")]
        [Required]
        public string nom { get; set; }
        [DisplayName("Prénom élève")]
        [Required]
        public string prenom { get; set; }
        [DisplayName("Date de naissance")]
        [Required]
        public System.DateTime date_naissance { get; set; } = DateTime.Now;
        [DisplayName("Promotion")]
        [Required]
        public Nullable<int> fk_eleve_promotion { get; set; }
    
        public virtual Promotions Promotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notes> Notes { get; set; }
    }
}
