//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotEduWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Notes
    {
        [DisplayName("Valeur")]
        [Required]
        [Range(0.00, 20.00, ErrorMessage = "La valeur doit être comprise entre 0.00 et 20.00.")]
        public decimal valeur { get; set; }
        [DisplayName("Appréciation")]
        public string appreciation { get; set; }
        [DisplayName("Elève")]
        [Required]
        public int fk_note_eleve { get; set; }
        [DisplayName("Cours")]
        [Required]
        public int fk_note_cours { get; set; }

        public virtual Cours Cours { get; set; }
        public virtual Eleves Eleves { get; set; }
    }
}
