DROP DATABASE IF EXISTS NotEduWeb
GO

CREATE DATABASE NotEduWeb
GO

USE NotEduWeb
GO

DROP TABLE IF EXISTS Promotions
CREATE TABLE Promotions(
	ID_promotion INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	annee INT NOT NULL,
	nom VARCHAR(50) NOT NULL,
)
GO

DROP TABLE IF EXISTS Eleves
CREATE TABLE Eleves(
	ID_eleve INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	nom VARCHAR(50) NOT NULL,
	prenom VARCHAR(50) NOT NULL,
	date_naissance DATETIME NOT NULL,
	fk_eleve_promotion INT FOREIGN KEY REFERENCES Promotions(ID_promotion)
)
GO

DROP TABLE IF EXISTS Cours
CREATE TABLE Cours(
	ID_cours INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	nom VARCHAR(50) NOT NULL
)
GO

DROP TABLE IF EXISTS Notes
CREATE TABLE Notes(
	valeur DECIMAL(4,2) NOT NULL,
	appreciation VARCHAR(max),
	fk_note_eleve INT FOREIGN KEY REFERENCES Eleves(ID_eleve) ON DELETE CASCADE,
	fk_note_cours INT FOREIGN KEY REFERENCES Cours(ID_cours) ON DELETE CASCADE,
	PRIMARY KEY (fk_note_eleve, fk_note_cours)
)
GO